version: 2
jobs:
  build-8:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "package.json" }}
          - node8-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test
    build-10:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - node10-dependencies-{{ checksum "package.json" }}
          - node10-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node10-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-8 
      - build-10